In [1]:
import sys
sys.path.append('/srv/Citi/jupyter-samples/')
from dev import io
%load_ext sql

In [2]:
io.excel2db(db_name='sample.db',excel_name='input1.xlsx')

In [3]:
%sql sqlite:///sample.db

'Connected: @sample.db'

In [4]:
%sql select name from sqlite_master;

 * sqlite:///sample.db
Done.

[('LoanStats3a',)]

In [5]:
%sql select * from LoanStats3a where loan_amnt > 4000 limit 1;

 * sqlite:///sample.db
Done.

[(None, None, 5000, 5000, 4975.0, ' 36 months', 0.1065, 162.87, 'B', 'B2', None, '10+ years', 'RENT', 24000.0, 'Verified', '2011-12-01 00:00:00', 'Fully Paid', 'n', None, '  Borrower added on 12/22/11 > I need to upgrade my business technologies.<br>', 'credit_card', 'Computer', '860xx', 'AZ', 27.65, 0, '1985-01-01 00:00:00', 1, None, None, 3, 0, 13648, 0.837, 9, 'f', 0, 0, 5863.1551866952, 5833.84, 5000.0, 863.16, 0.0, 0.0, 0.0, '2015-01-01 00:00:00', 171.62, None, '2018-02-01 00:00:00', 0, None, 1, 'Individual', None, None, None, 0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0, 0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0, 0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'N', None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'Cash', 'N', None, None, None, None, None, None)]

In [6]:
%sql pragma table_info(LoanStats3a);

 * sqlite:///sample.db
Done.

[(0, 'id', 'REAL', 0, None, 0),
 (1, 'member_id', 'REAL', 0, None, 0),
 (2, 'loan_amnt', 'INTEGER', 0, None, 0),
 (3, 'funded_amnt', 'INTEGER', 0, None, 0),
 (4, 'funded_amnt_inv', 'REAL', 0, None, 0),
 (5, 'term', 'TEXT', 0, None, 0),
 (6, 'int_rate', 'REAL', 0, None, 0),
 (7, 'installment', 'REAL', 0, None, 0),
 (8, 'grade', 'TEXT', 0, None, 0),
 (9, 'sub_grade', 'TEXT', 0, None, 0),
 (10, 'emp_title', 'TEXT', 0, None, 0),
 (11, 'emp_length', 'TEXT', 0, None, 0),
 (12, 'home_ownership', 'TEXT', 0, None, 0),
 (13, 'annual_inc', 'REAL', 0, None, 0),
 (14, 'verification_status', 'TEXT', 0, None, 0),
 (15, 'issue_d', 'TIMESTAMP', 0, None, 0),
 (16, 'loan_status', 'TEXT', 0, None, 0),
 (17, 'pymnt_plan', 'TEXT', 0, None, 0),
 (18, 'url', 'REAL', 0, None, 0),
 (19, 'desc', 'TEXT', 0, None, 0),
 (20, 'purpose', 'TEXT', 0, None, 0),
 (21, 'title', 'TEXT', 0, None, 0),
 (22, 'zip_code', 'TEXT', 0, None, 0),
 (23, 'addr_state', 'TEXT', 0, None, 0),
 (24, 'dti', 'REAL', 0, None, 0),
 (25, 'delinq_2yrs', 'INTEGER', 0, None, 0),
 (26, 'earliest_cr_line', 'TIMESTAMP', 0, None, 0),
 (27, 'inq_last_6mths', 'INTEGER', 0, None, 0),
 (28, 'mths_since_last_delinq', 'REAL', 0, None, 0),
 (29, 'mths_since_last_record', 'REAL', 0, None, 0),
 (30, 'open_acc', 'INTEGER', 0, None, 0),
 (31, 'pub_rec', 'INTEGER', 0, None, 0),
 (32, 'revol_bal', 'INTEGER', 0, None, 0),
 (33, 'revol_util', 'REAL', 0, None, 0),
 (34, 'total_acc', 'INTEGER', 0, None, 0),
 (35, 'initial_list_status', 'TEXT', 0, None, 0),
 (36, 'out_prncp', 'INTEGER', 0, None, 0),
 (37, 'out_prncp_inv', 'INTEGER', 0, None, 0),
 (38, 'total_pymnt', 'REAL', 0, None, 0),
 (39, 'total_pymnt_inv', 'REAL', 0, None, 0),
 (40, 'total_rec_prncp', 'REAL', 0, None, 0),
 (41, 'total_rec_int', 'REAL', 0, None, 0),
 (42, 'total_rec_late_fee', 'REAL', 0, None, 0),
 (43, 'recoveries', 'REAL', 0, None, 0),
 (44, 'collection_recovery_fee', 'REAL', 0, None, 0),
 (45, 'last_pymnt_d', 'TIMESTAMP', 0, None, 0),
 (46, 'last_pymnt_amnt', 'REAL', 0, None, 0),
 (47, 'next_pymnt_d', 'REAL', 0, None, 0),
 (48, 'last_credit_pull_d', 'TIMESTAMP', 0, None, 0),
 (49, 'collections_12_mths_ex_med', 'INTEGER', 0, None, 0),
 (50, 'mths_since_last_major_derog', 'REAL', 0, None, 0),
 (51, 'policy_code', 'INTEGER', 0, None, 0),
 (52, 'application_type', 'TEXT', 0, None, 0),
 (53, 'annual_inc_joint', 'REAL', 0, None, 0),
 (54, 'dti_joint', 'REAL', 0, None, 0),
 (55, 'verification_status_joint', 'REAL', 0, None, 0),
 (56, 'acc_now_delinq', 'INTEGER', 0, None, 0),
 (57, 'tot_coll_amt', 'REAL', 0, None, 0),
 (58, 'tot_cur_bal', 'REAL', 0, None, 0),
 (59, 'open_acc_6m', 'REAL', 0, None, 0),
 (60, 'open_act_il', 'REAL', 0, None, 0),
 (61, 'open_il_12m', 'REAL', 0, None, 0),
 (62, 'open_il_24m', 'REAL', 0, None, 0),
 (63, 'mths_since_rcnt_il', 'REAL', 0, None, 0),
 (64, 'total_bal_il', 'REAL', 0, None, 0),
 (65, 'il_util', 'REAL', 0, None, 0),
 (66, 'open_rv_12m', 'REAL', 0, None, 0),
 (67, 'open_rv_24m', 'REAL', 0, None, 0),
 (68, 'max_bal_bc', 'REAL', 0, None, 0),
 (69, 'all_util', 'REAL', 0, None, 0),
 (70, 'total_rev_hi_lim', 'REAL', 0, None, 0),
 (71, 'inq_fi', 'REAL', 0, None, 0),
 (72, 'total_cu_tl', 'REAL', 0, None, 0),
 (73, 'inq_last_12m', 'REAL', 0, None, 0),
 (74, 'acc_open_past_24mths', 'REAL', 0, None, 0),
 (75, 'avg_cur_bal', 'REAL', 0, None, 0),
 (76, 'bc_open_to_buy', 'REAL', 0, None, 0),
 (77, 'bc_util', 'REAL', 0, None, 0),
 (78, 'chargeoff_within_12_mths', 'INTEGER', 0, None, 0),
 (79, 'delinq_amnt', 'INTEGER', 0, None, 0),
 (80, 'mo_sin_old_il_acct', 'REAL', 0, None, 0),
 (81, 'mo_sin_old_rev_tl_op', 'REAL', 0, None, 0),
 (82, 'mo_sin_rcnt_rev_tl_op', 'REAL', 0, None, 0),
 (83, 'mo_sin_rcnt_tl', 'REAL', 0, None, 0),
 (84, 'mort_acc', 'REAL', 0, None, 0),
 (85, 'mths_since_recent_bc', 'REAL', 0, None, 0),
 (86, 'mths_since_recent_bc_dlq', 'REAL', 0, None, 0),
 (87, 'mths_since_recent_inq', 'REAL', 0, None, 0),
 (88, 'mths_since_recent_revol_delinq', 'REAL', 0, None, 0),
 (89, 'num_accts_ever_120_pd', 'REAL', 0, None, 0),
 (90, 'num_actv_bc_tl', 'REAL', 0, None, 0),
 (91, 'num_actv_rev_tl', 'REAL', 0, None, 0),
 (92, 'num_bc_sats', 'REAL', 0, None, 0),
 (93, 'num_bc_tl', 'REAL', 0, None, 0),
 (94, 'num_il_tl', 'REAL', 0, None, 0),
 (95, 'num_op_rev_tl', 'REAL', 0, None, 0),
 (96, 'num_rev_accts', 'REAL', 0, None, 0),
 (97, 'num_rev_tl_bal_gt_0', 'REAL', 0, None, 0),
 (98, 'num_sats', 'REAL', 0, None, 0),
 (99, 'num_tl_120dpd_2m', 'REAL', 0, None, 0),
 (100, 'num_tl_30dpd', 'REAL', 0, None, 0),
 (101, 'num_tl_90g_dpd_24m', 'REAL', 0, None, 0),
 (102, 'num_tl_op_past_12m', 'REAL', 0, None, 0),
 (103, 'pct_tl_nvr_dlq', 'REAL', 0, None, 0),
 (104, 'percent_bc_gt_75', 'REAL', 0, None, 0),
 (105, 'pub_rec_bankruptcies', 'INTEGER', 0, None, 0),
 (106, 'tax_liens', 'INTEGER', 0, None, 0),
 (107, 'tot_hi_cred_lim', 'REAL', 0, None, 0),
 (108, 'total_bal_ex_mort', 'REAL', 0, None, 0),
 (109, 'total_bc_limit', 'REAL', 0, None, 0),
 (110, 'total_il_high_credit_limit', 'REAL', 0, None, 0),
 (111, 'revol_bal_joint', 'REAL', 0, None, 0),
 (112, 'sec_app_earliest_cr_line', 'REAL', 0, None, 0),
 (113, 'sec_app_inq_last_6mths', 'REAL', 0, None, 0),
 (114, 'sec_app_mort_acc', 'REAL', 0, None, 0),
 (115, 'sec_app_open_acc', 'REAL', 0, None, 0),
 (116, 'sec_app_revol_util', 'REAL', 0, None, 0),
 (117, 'sec_app_open_act_il', 'REAL', 0, None, 0),
 (118, 'sec_app_num_rev_accts', 'REAL', 0, None, 0),
 (119, 'sec_app_chargeoff_within_12_mths', 'REAL', 0, None, 0),
 (120, 'sec_app_collections_12_mths_ex_med', 'REAL', 0, None, 0),
 (121, 'sec_app_mths_since_last_major_derog', 'REAL', 0, None, 0),
 (122, 'hardship_flag', 'TEXT', 0, None, 0),
 (123, 'hardship_type', 'REAL', 0, None, 0),
 (124, 'hardship_reason', 'REAL', 0, None, 0),
 (125, 'hardship_status', 'REAL', 0, None, 0),
 (126, 'deferral_term', 'REAL', 0, None, 0),
 (127, 'hardship_amount', 'REAL', 0, None, 0),
 (128, 'hardship_start_date', 'REAL', 0, None, 0),
 (129, 'hardship_end_date', 'REAL', 0, None, 0),
 (130, 'payment_plan_start_date', 'REAL', 0, None, 0),
 (131, 'hardship_length', 'REAL', 0, None, 0),
 (132, 'hardship_dpd', 'REAL', 0, None, 0),
 (133, 'hardship_loan_status', 'REAL', 0, None, 0),
 (134, 'orig_projected_additional_accrued_interest', 'REAL', 0, None, 0),
 (135, 'hardship_payoff_balance_amount', 'REAL', 0, None, 0),
 (136, 'hardship_last_payment_amount', 'REAL', 0, None, 0),
 (137, 'disbursement_method', 'TEXT', 0, None, 0),
 (138, 'debt_settlement_flag', 'TEXT', 0, None, 0),
 (139, 'debt_settlement_flag_date', 'TIMESTAMP', 0, None, 0),
 (140, 'settlement_status', 'TEXT', 0, None, 0),
 (141, 'settlement_date', 'TIMESTAMP', 0, None, 0),
 (142, 'settlement_amount', 'REAL', 0, None, 0),
 (143, 'settlement_percentage', 'REAL', 0, None, 0),
 (144, 'settlement_term', 'REAL', 0, None, 0)]

In [7]:
io.renameDbColumns(database_name='sample.db', fields_map={"id":"NewID"})

In [8]:
from mycode import *

In [9]:
calc2Plus2()

4

In [10]:
io.listColumnsInDB('sample.db', 'LoanStats3a')

[(0, 'NewID', 'TEXT', 0, None, 0),
 (1, 'member_id', 'TEXT', 0, None, 0),
 (2, 'loan_amnt', 'INTEGER', 0, None, 0),
 (3, 'funded_amnt', 'INTEGER', 0, None, 0),
 (4, 'funded_amnt_inv', 'REAL', 0, None, 0),
 (5, 'term', 'TEXT', 0, None, 0),
 (6, 'int_rate', 'REAL', 0, None, 0),
 (7, 'installment', 'REAL', 0, None, 0),
 (8, 'grade', 'TEXT', 0, None, 0),
 (9, 'sub_grade', 'TEXT', 0, None, 0),
 (10, 'emp_title', 'TEXT', 0, None, 0),
 (11, 'emp_length', 'TEXT', 0, None, 0),
 (12, 'home_ownership', 'TEXT', 0, None, 0),
 (13, 'annual_inc', 'REAL', 0, None, 0),
 (14, 'verification_status', 'TEXT', 0, None, 0),
 (15, 'issue_d', 'TEXT', 0, None, 0),
 (16, 'loan_status', 'TEXT', 0, None, 0),
 (17, 'pymnt_plan', 'TEXT', 0, None, 0),
 (18, 'url', 'TEXT', 0, None, 0),
 (19, 'desc', 'TEXT', 0, None, 0),
 (20, 'purpose', 'TEXT', 0, None, 0),
 (21, 'title', 'TEXT', 0, None, 0),
 (22, 'zip_code', 'TEXT', 0, None, 0),
 (23, 'addr_state', 'TEXT', 0, None, 0),
 (24, 'dti', 'REAL', 0, None, 0),
 (25, 'delinq_2yrs', 'INTEGER', 0, None, 0),
 (26, 'earliest_cr_line', 'TEXT', 0, None, 0),
 (27, 'inq_last_6mths', 'INTEGER', 0, None, 0),
 (28, 'mths_since_last_delinq', 'REAL', 0, None, 0),
 (29, 'mths_since_last_record', 'REAL', 0, None, 0),
 (30, 'open_acc', 'INTEGER', 0, None, 0),
 (31, 'pub_rec', 'INTEGER', 0, None, 0),
 (32, 'revol_bal', 'INTEGER', 0, None, 0),
 (33, 'revol_util', 'REAL', 0, None, 0),
 (34, 'total_acc', 'INTEGER', 0, None, 0),
 (35, 'initial_list_status', 'TEXT', 0, None, 0),
 (36, 'out_prncp', 'INTEGER', 0, None, 0),
 (37, 'out_prncp_inv', 'INTEGER', 0, None, 0),
 (38, 'total_pymnt', 'REAL', 0, None, 0),
 (39, 'total_pymnt_inv', 'REAL', 0, None, 0),
 (40, 'total_rec_prncp', 'REAL', 0, None, 0),
 (41, 'total_rec_int', 'REAL', 0, None, 0),
 (42, 'total_rec_late_fee', 'REAL', 0, None, 0),
 (43, 'recoveries', 'REAL', 0, None, 0),
 (44, 'collection_recovery_fee', 'REAL', 0, None, 0),
 (45, 'last_pymnt_d', 'TEXT', 0, None, 0),
 (46, 'last_pymnt_amnt', 'REAL', 0, None, 0),
 (47, 'next_pymnt_d', 'TEXT', 0, None, 0),
 (48, 'last_credit_pull_d', 'TEXT', 0, None, 0),
 (49, 'collections_12_mths_ex_med', 'INTEGER', 0, None, 0),
 (50, 'mths_since_last_major_derog', 'TEXT', 0, None, 0),
 (51, 'policy_code', 'INTEGER', 0, None, 0),
 (52, 'application_type', 'TEXT', 0, None, 0),
 (53, 'annual_inc_joint', 'TEXT', 0, None, 0),
 (54, 'dti_joint', 'TEXT', 0, None, 0),
 (55, 'verification_status_joint', 'TEXT', 0, None, 0),
 (56, 'acc_now_delinq', 'INTEGER', 0, None, 0),
 (57, 'tot_coll_amt', 'TEXT', 0, None, 0),
 (58, 'tot_cur_bal', 'TEXT', 0, None, 0),
 (59, 'open_acc_6m', 'TEXT', 0, None, 0),
 (60, 'open_act_il', 'TEXT', 0, None, 0),
 (61, 'open_il_12m', 'TEXT', 0, None, 0),
 (62, 'open_il_24m', 'TEXT', 0, None, 0),
 (63, 'mths_since_rcnt_il', 'TEXT', 0, None, 0),
 (64, 'total_bal_il', 'TEXT', 0, None, 0),
 (65, 'il_util', 'TEXT', 0, None, 0),
 (66, 'open_rv_12m', 'TEXT', 0, None, 0),
 (67, 'open_rv_24m', 'TEXT', 0, None, 0),
 (68, 'max_bal_bc', 'TEXT', 0, None, 0),
 (69, 'all_util', 'TEXT', 0, None, 0),
 (70, 'total_rev_hi_lim', 'TEXT', 0, None, 0),
 (71, 'inq_fi', 'TEXT', 0, None, 0),
 (72, 'total_cu_tl', 'TEXT', 0, None, 0),
 (73, 'inq_last_12m', 'TEXT', 0, None, 0),
 (74, 'acc_open_past_24mths', 'TEXT', 0, None, 0),
 (75, 'avg_cur_bal', 'TEXT', 0, None, 0),
 (76, 'bc_open_to_buy', 'TEXT', 0, None, 0),
 (77, 'bc_util', 'TEXT', 0, None, 0),
 (78, 'chargeoff_within_12_mths', 'INTEGER', 0, None, 0),
 (79, 'delinq_amnt', 'INTEGER', 0, None, 0),
 (80, 'mo_sin_old_il_acct', 'TEXT', 0, None, 0),
 (81, 'mo_sin_old_rev_tl_op', 'TEXT', 0, None, 0),
 (82, 'mo_sin_rcnt_rev_tl_op', 'TEXT', 0, None, 0),
 (83, 'mo_sin_rcnt_tl', 'TEXT', 0, None, 0),
 (84, 'mort_acc', 'TEXT', 0, None, 0),
 (85, 'mths_since_recent_bc', 'TEXT', 0, None, 0),
 (86, 'mths_since_recent_bc_dlq', 'TEXT', 0, None, 0),
 (87, 'mths_since_recent_inq', 'TEXT', 0, None, 0),
 (88, 'mths_since_recent_revol_delinq', 'TEXT', 0, None, 0),
 (89, 'num_accts_ever_120_pd', 'TEXT', 0, None, 0),
 (90, 'num_actv_bc_tl', 'TEXT', 0, None, 0),
 (91, 'num_actv_rev_tl', 'TEXT', 0, None, 0),
 (92, 'num_bc_sats', 'TEXT', 0, None, 0),
 (93, 'num_bc_tl', 'TEXT', 0, None, 0),
 (94, 'num_il_tl', 'TEXT', 0, None, 0),
 (95, 'num_op_rev_tl', 'TEXT', 0, None, 0),
 (96, 'num_rev_accts', 'TEXT', 0, None, 0),
 (97, 'num_rev_tl_bal_gt_0', 'TEXT', 0, None, 0),
 (98, 'num_sats', 'TEXT', 0, None, 0),
 (99, 'num_tl_120dpd_2m', 'TEXT', 0, None, 0),
 (100, 'num_tl_30dpd', 'TEXT', 0, None, 0),
 (101, 'num_tl_90g_dpd_24m', 'TEXT', 0, None, 0),
 (102, 'num_tl_op_past_12m', 'TEXT', 0, None, 0),
 (103, 'pct_tl_nvr_dlq', 'TEXT', 0, None, 0),
 (104, 'percent_bc_gt_75', 'TEXT', 0, None, 0),
 (105, 'pub_rec_bankruptcies', 'INTEGER', 0, None, 0),
 (106, 'tax_liens', 'INTEGER', 0, None, 0),
 (107, 'tot_hi_cred_lim', 'TEXT', 0, None, 0),
 (108, 'total_bal_ex_mort', 'TEXT', 0, None, 0),
 (109, 'total_bc_limit', 'TEXT', 0, None, 0),
 (110, 'total_il_high_credit_limit', 'TEXT', 0, None, 0),
 (111, 'revol_bal_joint', 'TEXT', 0, None, 0),
 (112, 'sec_app_earliest_cr_line', 'TEXT', 0, None, 0),
 (113, 'sec_app_inq_last_6mths', 'TEXT', 0, None, 0),
 (114, 'sec_app_mort_acc', 'TEXT', 0, None, 0),
 (115, 'sec_app_open_acc', 'TEXT', 0, None, 0),
 (116, 'sec_app_revol_util', 'TEXT', 0, None, 0),
 (117, 'sec_app_open_act_il', 'TEXT', 0, None, 0),
 (118, 'sec_app_num_rev_accts', 'TEXT', 0, None, 0),
 (119, 'sec_app_chargeoff_within_12_mths', 'TEXT', 0, None, 0),
 (120, 'sec_app_collections_12_mths_ex_med', 'TEXT', 0, None, 0),
 (121, 'sec_app_mths_since_last_major_derog', 'TEXT', 0, None, 0),
 (122, 'hardship_flag', 'TEXT', 0, None, 0),
 (123, 'hardship_type', 'TEXT', 0, None, 0),
 (124, 'hardship_reason', 'TEXT', 0, None, 0),
 (125, 'hardship_status', 'TEXT', 0, None, 0),
 (126, 'deferral_term', 'TEXT', 0, None, 0),
 (127, 'hardship_amount', 'TEXT', 0, None, 0),
 (128, 'hardship_start_date', 'TEXT', 0, None, 0),
 (129, 'hardship_end_date', 'TEXT', 0, None, 0),
 (130, 'payment_plan_start_date', 'TEXT', 0, None, 0),
 (131, 'hardship_length', 'TEXT', 0, None, 0),
 (132, 'hardship_dpd', 'TEXT', 0, None, 0),
 (133, 'hardship_loan_status', 'TEXT', 0, None, 0),
 (134, 'orig_projected_additional_accrued_interest', 'TEXT', 0, None, 0),
 (135, 'hardship_payoff_balance_amount', 'TEXT', 0, None, 0),
 (136, 'hardship_last_payment_amount', 'TEXT', 0, None, 0),
 (137, 'disbursement_method', 'TEXT', 0, None, 0),
 (138, 'debt_settlement_flag', 'TEXT', 0, None, 0),
 (139, 'debt_settlement_flag_date', 'TEXT', 0, None, 0),
 (140, 'settlement_status', 'TEXT', 0, None, 0),
 (141, 'settlement_date', 'TEXT', 0, None, 0),
 (142, 'settlement_amount', 'REAL', 0, None, 0),
 (143, 'settlement_percentage', 'REAL', 0, None, 0),
 (144, 'settlement_term', 'REAL', 0, None, 0)]

In [15]:
%sql select count(*) from LoanStats3a;

 * sqlite:///sample.db
Done.

[(933,)]

In [14]:
%sql delete from LoanStats3a where loan_amnt < 4000;

 * sqlite:///sample.db
0 rows affected.

[]